DROP DATABASE IF EXISTS SPA;
CREATE DATABASE SPA;
USE SPA;


CREATE TABLE tb_CLIENTE(
ID_CLI INT PRIMARY KEY AUTO_INCREMENT,
NOME_CLI TEXT NOT NULL,
EMAIL_CLI VARCHAR(200) NOT NULL,
SENHA_CLI VARCHAR(8) NOT NULL,
TELEFONE_CLI VARCHAR(16) NOT NULL
);

select * from tb_CLIENTE;

CREATE TABLE tb_RESERVA(
COD_RES INT PRIMARY KEY AUTO_INCREMENT,
EMAIL_CLI VARCHAR(200) REFERENCES tb_CLIENTE (COD_CLI) ON UPDATE CASCADE ON DELETE CASCADE,
RESERVA_DATA DATE NOT NULL,
RESERVA_QTD INT
);

CREATE TABLE tb_FUNCIONARIOS(
COD_FUN integer PRIMARY KEY AUTO_INCREMENT,
NOME_FUN TEXT NOT NULL,
EMAIL_FUN VARCHAR (200),
SENHA_FUN VARCHAR (8) NOT NULL,
TELEFONE_FUN VARCHAR(14) NOT NULL,
RG_FUN Varchar(12) NOT NULL,
CPF_FUN VARCHAR(14) NOT NULL,
CEP_FUN Varchar(9) NOT NULL,
CIDADE_FUN Text NOT NULL,
IDADE_FUN VARCHAR(2) NOT NULL,
CARGO_FUN TEXT NOT NULL
);

select * from tb_FUNCIONARIOS;